# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

if __name__ == '__main__':
    got, want = 0, 4613732
    prev, next = 0, 1
    while next < 4000000:
        prev, next = next, prev + next
        if next % 2 == 0:
            got += next
    print('got:{} == want:{} = {}'.format(got, want, got == want))
